# Generated by Django 3.2.7 on 2021-10-29 13:35

from django.db import migrations, models
import django.db.models.deletion
import exam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuongCauHoi', models.PositiveSmallIntegerField()),
                ('file', models.FileField(upload_to='deThi/')),
                ('key', models.CharField(default=exam.models._createHash, max_length=8, unique=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofiles.giangvien')),
            ],
        ),
        migrations.CreateModel(
            name='PhongThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenPhongThi', models.CharField(blank=True, max_length=200)),
                ('siSo', models.PositiveSmallIntegerField()),
                ('danhSach', models.FileField(upload_to='danhSachPhongThi/')),
                ('thoiGianLamBai', models.PositiveSmallIntegerField()),
                ('thoiGianThi', models.DateTimeField()),
                ('namHoc', models.CharField(max_length=11)),
                ('hocKi', models.PositiveIntegerField()),
                ('deThi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phongthi', to='exam.dethi')),
                ('giangVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofiles.giangvien')),
            ],
        ),
        migrations.CreateModel(
            name='DiemThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baiLam', models.TextField(blank=True)),
                ('diem', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('phongThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.phongthi')),
                ('sinhVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofiles.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDeThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.PositiveSmallIntegerField()),
                ('noiDung', models.TextField()),
                ('dapAn', models.PositiveSmallIntegerField()),
                ('deThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.dethi')),
            ],
        ),
        migrations.AddConstraint(
            model_name='diemthi',
            constraint=models.UniqueConstraint(fields=('sinhVien', 'phongThi'), name='unique Sv PhongThi'),
        ),
    ]
