# Generated by Django 3.2.7 on 2022-01-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_phongthi_dethi'),
    ]

    operations = [
        migrations.AddField(
            model_name='dethi',
            name='kieuThi',
            field=models.BooleanField(choices=[(False, 'Tự luận'), (True, 'Trắc nghiệm')], default=True),
        ),
        migrations.AddField(
            model_name='diemthi',
            name='baiLamTuLuan',
            field=models.FileField(blank=True, upload_to='baiLamTuLuan/'),
        ),
    ]
