# Generated by Django 3.2.7 on 2022-01-15 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20220113_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiemTuLuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileDiem', models.FileField(upload_to='diemTuLuan/')),
                ('phongThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.phongthi')),
            ],
        ),
    ]
