# Generated by Django 3.2.7 on 2021-11-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211102_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar/default.png', upload_to='avatar/'),
        ),
    ]
