# Generated by Django 3.2.7 on 2021-10-04 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='school_account',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='teacher_account',
        ),
    ]
