# Generated by Django 3.2.7 on 2021-10-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211004_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
    ]
