# Generated by Django 3.2.7 on 2021-10-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountbulkcreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbulkcreate',
            name='type',
            field=models.CharField(choices=[('T', 'Giảng viên'), ('S', 'Sinh viên')], default='S', max_length=1),
        ),
    ]
