# Generated by Django 3.2.7 on 2021-10-22 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_accountbulkcreate_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truong',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='scinfo', serialize=False, to='accounts.customuser')),
                ('school_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='sid',
        ),
        migrations.AddField(
            model_name='customuser',
            name='student',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stinfo', serialize=False, to='accounts.customuser')),
                ('full_name', models.CharField(blank=True, max_length=40)),
                ('sex', models.CharField(blank=True, max_length=1)),
                ('cid', models.CharField(blank=True, max_length=12)),
                ('sid', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.truong')),
            ],
        ),
        migrations.CreateModel(
            name='GiangVien',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='gvinfo', serialize=False, to='accounts.customuser')),
                ('full_name', models.CharField(blank=True, max_length=40)),
                ('sex', models.CharField(blank=True, max_length=1)),
                ('cid', models.CharField(blank=True, max_length=12)),
                ('sid', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(blank=True, max_length=12)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.truong')),
            ],
        ),
    ]
