# Generated by Django 3.2.7 on 2021-10-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211022_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soLuongCauHoi', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhongThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenPhongThi', models.CharField(blank=True, max_length=200)),
                ('siSo', models.PositiveSmallIntegerField()),
                ('danhSach', models.FileField(upload_to='danhSachPhongThi/')),
                ('thoiGianLamBai', models.PositiveSmallIntegerField()),
                ('thoiGianThi', models.DateTimeField()),
                ('namHoc', models.CharField(max_length=11)),
                ('hocKi', models.PositiveIntegerField()),
                ('deThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dethi')),
                ('giangVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.giangvien')),
            ],
        ),
        migrations.CreateModel(
            name='DiemThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diem', models.DecimalField(decimal_places=2, max_digits=4)),
                ('phongThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.phongthi')),
                ('sinhVien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.sinhvien')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietDeThi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noiDung', models.TextField()),
                ('dapAn', models.PositiveSmallIntegerField()),
                ('deThi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.dethi')),
            ],
        ),
        migrations.AddConstraint(
            model_name='diemthi',
            constraint=models.UniqueConstraint(fields=('sinhVien', 'phongThi'), name='unique Sv PhongThi'),
        ),
    ]
